import React, { useMemo, useState } from "react";
import { useSystem } from "../../context/SystemContext";
import Modal from "../../components/ui/Modal";
import { exportarEstoquePDF } from "../../services/reportService";

export default function Estoque() {
  const { itens, departamentos, nivelUsuario, user, getNomeDepartamento, handleSalvarEdicao, confirmarExclusao, enviarSolicitacao, mostrarNotificacao } = useSystem();
  const [busca, setBusca] = useState(""); const [categoria, setCategoria] = useState(""); const [pagina, setPagina] = useState(1);
  const [editando, setEditando] = useState(null); const [excluir, setExcluir] = useState(null);
  const [solicitar, setSolicitar] = useState(null); const porPagina = 50;
  const categorias = useMemo(() => [...new Set(itens.map(i => i.categoria).filter(Boolean))].sort(), [itens]);
  const filtrados = useMemo(() => itens.filter(i => i.nome.toLowerCase().includes(busca.toLowerCase()) && (!categoria || i.categoria === categoria)), [itens, busca, categoria]);
  const total = Math.max(1, Math.ceil(filtrados.length / porPagina)); const atuais = filtrados.slice((pagina - 1) * porPagina, pagina * porPagina);
  const submitEdit = async e => { if (await handleSalvarEdicao(e, editando)) setEditando(null); };
  const submitSolic = async e => { if (await enviarSolicitacao(e, solicitar)) setSolicitar(null); };

  return <section className="page-section">
    <div className="page-heading"><div><span className="eyebrow">INVENTÁRIO</span><h2>Estoque Geral</h2><p>Visualize os materiais disponíveis por departamento.</p></div><button className="btn btn-secondary" onClick={() => { exportarEstoquePDF(filtrados, getNomeDepartamento); mostrarNotificacao("Download do PDF concluído!"); }}>Exportar PDF</button></div>
    <div className="toolbar"><input placeholder="Pesquisar material..." value={busca} onChange={e => {setBusca(e.target.value); setPagina(1);}} /><select value={categoria} onChange={e => {setCategoria(e.target.value); setPagina(1);}}><option value="">Todas as categorias</option>{categorias.map(c => <option key={c}>{c}</option>)}</select><span className="result-count">{filtrados.length} itens</span></div>
    <div className="table-card"><div className="table-scroll"><table><thead><tr><th>ID</th><th>Material</th><th>Categoria</th><th>Departamento</th><th>Quantidade</th><th>Localização</th><th>Ações</th></tr></thead><tbody>
      {atuais.map(i => { const meu = i.departamento_id === user.departamento_id; const podeEditar = meu || nivelUsuario === 0; const podeExcluir = (meu && nivelUsuario <= 1) || nivelUsuario === 0; const alerta = i.quantidade <= i.quantidade_minima; return <tr key={i.id} className={alerta ? "row-alert" : ""}><td>#{i.id}</td><td className="strong">{i.nome}</td><td>{i.categoria}</td><td>{i.departamentos?.nome || getNomeDepartamento(i.departamento_id)}</td><td><span className={alerta ? "qty-danger" : "qty"}>{i.quantidade}</span>{alerta && <span title="Estoque mínimo atingido"> ⚠</span>}</td><td>{i.localizacao || "—"}</td><td><div className="action-row">{podeEditar ? <><button className="btn btn-small btn-edit" onClick={() => setEditando({...i})}>Editar</button>{podeExcluir && <button className="btn btn-small btn-danger" onClick={() => setExcluir(i)}>Excluir</button>}</> : <button className="btn btn-small btn-secondary" onClick={() => setSolicitar({ item: i, quantidade: 1, observacao: "" })}>Solicitar</button>}</div></td></tr>})}
      {!atuais.length && <tr><td colSpan="7" className="empty-state">Nenhum material encontrado.</td></tr>}
    </tbody></table></div></div>
    {total > 1 && <div className="pagination"><button className="btn btn-small" disabled={pagina === 1} onClick={() => setPagina(pagina - 1)}>Anterior</button><span>Página {pagina} de {total}</span><button className="btn btn-small" disabled={pagina === total} onClick={() => setPagina(pagina + 1)}>Próxima</button></div>}

    <Modal open={!!editando} title="Editar Material" onClose={() => setEditando(null)}><form className="form-stack" onSubmit={submitEdit}><label>Nome<input required value={editando?.nome || ""} onChange={e => setEditando({...editando, nome:e.target.value})}/></label><label>Categoria<input required value={editando?.categoria || ""} onChange={e => setEditando({...editando, categoria:e.target.value})}/></label><div className="form-grid"><label>Quantidade<input type="number" min="0" required value={editando?.quantidade ?? ""} onChange={e => setEditando({...editando, quantidade:e.target.value})}/></label><label>Alerta mínimo<input type="number" min="0" required value={editando?.quantidade_minima ?? 0} onChange={e => setEditando({...editando, quantidade_minima:e.target.value})}/></label></div><label>Localização<input required value={editando?.localizacao || ""} onChange={e => setEditando({...editando, localizacao:e.target.value})}/></label><div className="modal-actions"><button className="btn btn-primary">Salvar alterações</button><button type="button" className="btn" onClick={() => setEditando(null)}>Cancelar</button></div></form></Modal>
    <Modal open={!!excluir} title="Excluir material" onClose={() => setExcluir(null)}><p>Deseja excluir permanentemente <strong>{excluir?.nome}</strong>?</p><div className="modal-actions"><button className="btn btn-danger" onClick={async()=>{await confirmarExclusao(excluir);setExcluir(null)}}>Sim, excluir</button><button className="btn" onClick={()=>setExcluir(null)}>Cancelar</button></div></Modal>
    <Modal open={!!solicitar} title="Solicitar Material" onClose={() => setSolicitar(null)}><form className="form-stack" onSubmit={submitSolic}><p>Solicitando <strong>{solicitar?.item.nome}</strong> do departamento <strong>{getNomeDepartamento(solicitar?.item.departamento_id)}</strong>.</p><label>Quantidade<input type="number" min="1" max={solicitar?.item.quantidade} required value={solicitar?.quantidade || 1} onChange={e=>setSolicitar({...solicitar, quantidade:e.target.value})}/></label><label>Observação<textarea maxLength="500" value={solicitar?.observacao || ""} onChange={e=>setSolicitar({...solicitar, observacao:e.target.value})}/></label><div className="modal-actions"><button className="btn btn-primary">Enviar pedido</button><button type="button" className="btn" onClick={()=>setSolicitar(null)}>Cancelar</button></div></form></Modal>
  </section>;
}
